name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libx11-dev libxext-dev libbsd-dev xvfb

      - name: Build
        run: make

      - name: Run sample execution
        run: timeout 5 xvfb-run ./cub3d sample.cub
